name: WARMer
channels:
    - defaults
dependencies:
    - python=3.9.7      # conda solver runs into irresolvable conflicts for 3.10.0 as of 10/26/2021
    - pandas=1.3.3
    - numpy=1.21.2
    - spyder            # or any other IDE

#    - pip:
        #- tabula-py==2.2.0      # PDF reader
        #- "git+https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-Listegg=fedelemflowlist"